In [1]:
import numpy as np
a = np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [9]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c=0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("for loop:" + str(1000*(toc-tic)) + "ms")

249747.145453
Vectorized version:7.6580047607421875ms
249747.145453
for loop:901.6120433807373ms


In [10]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [11]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [12]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [13]:
 import numpy as np
    
a = np.random.randn(5)

In [14]:
print(a)

[ 0.99979503 -0.30298914  0.10602554 -0.05576697 -0.75423662]


In [15]:
print(a.shape)

(5,)


In [16]:
print(a.T)

[ 0.99979503 -0.30298914  0.10602554 -0.05576697 -0.75423662]


In [17]:
print(np.dot(a,a.T))

1.67461676277


In [21]:
a = np.random.randn(5,1)
print(a)

[[ 0.16190041]
 [-1.0987309 ]
 [-1.69814242]
 [ 0.79537433]
 [-0.59090372]]


In [22]:
print(a.T)

[[ 0.16190041 -1.0987309  -1.69814242  0.79537433 -0.59090372]]


In [23]:
print(np.dot(a,a.T))

[[ 0.02621174 -0.17788498 -0.27492995  0.12877143 -0.09566755]
 [-0.17788498  1.20720959  1.86580155 -0.87390235  0.64924417]
 [-0.27492995  1.86580155  2.88368768 -1.35065888  1.00343867]
 [ 0.12877143 -0.87390235 -1.35065888  0.63262032 -0.46998964]
 [-0.09566755  0.64924417  1.00343867 -0.46998964  0.3491672 ]]
